### ISSUE TITLE
readthedocs: build error.

### ISSUE THREAD

**Issue by KaKkouo** [KaKkouo/sphindexer#11]
### command

```
/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
```

### error

```
_build/doctrees -D language=en . _build/html
Running Sphinx v4.2.0
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 237, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 429, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/sphinxcontrib/seqdiag.py", line 26, in <module>
    import seqdiag.utils.rst.nodes
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/seqdiag/utils/rst/nodes.py", line 16, in <module>
    from blockdiag.utils.rst import nodes
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/blockdiag/utils/rst/nodes.py", line 21, in <module>
    import blockdiag.builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/blockdiag/builder.py", line 16, in <module>
    from blockdiag import parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/blockdiag/parser.py", line 42, in <module>
    from funcparserlib.lexer import LexerError, Token, make_tokenizer
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/funcparserlib/lexer.py", line 80
    def match_specs(specs, str, i, (line, pos)):
                                   ^
SyntaxError: invalid syntax

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/blockdiag/parser.py", line 42, in <module>
    from funcparserlib.lexer import LexerError, Token, make_tokenizer
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/lib/python3.7/site-packages/funcparserlib/lexer.py", line 80
    def match_specs(specs, str, i, (line, pos)):
                                   ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-h4crb4b4.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by KaKkouo** [comment]
### 確認したこと

同じはずのコマンドをローカルで実行してもエラーにならない

```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
```

実行時のpythonを3.8にしてもエラーが変わらない。

funcparserlibで発生するエラーのため、ローカルと比べたらエラーが発生しているバージョンではない。このため、最新バージョンにしてみようとするが、それがエラーになる

```
/home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/bin/python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
```

```
Collecting funcparserlib==0.3.6
  Downloading funcparserlib-0.3.6.tar.gz (30 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/sphindexer/envs/latest/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bevsnuar/funcparserlib_526243a988214f229b102ce81351adc4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bevsnuar/funcparserlib_526243a988214f229b102ce81351adc4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zxhy3eaa
       cwd: /tmp/pip-install-bevsnuar/funcparserlib_526243a988214f229b102ce81351adc4/
  Complete output (1 lines):
  error in funcparserlib setup command: use_2to3 is invalid.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cb/f7/b4a59c3ccf67c0082546eaeb454da1a6610e924d2e7a2a21f337ecae7b40/funcparserlib-0.3.6.tar.gz#sha256=b7992eac1a3eb97b3d91faa342bfda0729e990bd8a43774c1592c091e563c91d (from https://pypi.org/simple/funcparserlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement funcparserlib==0.3.6 (from versions: 0.3, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 1.0.0a0)
ERROR: No matching distribution found for funcparserlib==0.3.6
```

**Comment by KaKkouo** [comment]
プレリリースの「funcparserlib 1.0.0a0」を指定したら、ビルドできた。

```
funcparserlib == 1.0.0a0
sphinxcontrib-seqdiag
sphindexer
```
